### PR TITLE
Fix #538 

### LINKED ISSUE #538: Neo4j client waits forever for lock leading to goroutines getting blocked
## Bug
In my production environment, I am using querying neo4J for some data in a Golang service. This service is deployed on multiple instances but on one instance, we found that the server stopped responding and the last log was just before executing the neo4j query. We added a few logs and added profiling, and this issue happened again, this time in another machine. When we checked the profile, we saw that the number of goroutines kept on increasing, and the graph shows this...

Neo4j lock issue (1)

Upon taking the entire dump of the goroutine's stack, it is evident that `getOrUpdateTable` method is waiting for the lock.

```
goroutine 4374599 [sync.Mutex.Lock, 157 minutes]:
sync.runtime_SemacquireMutex(0xc0068a48b8?, 0x18?, 0xc0068a4948?)
	/usr/local/go/src/runtime/sema.go:77 +0x25
sync.(*Mutex).lockSlow(0xc00027c528)
	/usr/local/go/src/sync/mutex.go:171 +0x15d
sync.(*Mutex).Lock(...)
	/usr/local/go/src/sync/mutex.go:90
github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/router.(*Router).getOrUpdateTable(0xc00027c500, {0x1ca5630, 0xc008772dc0}, 0x189fe40?, {0x1996373, 0x5}, 0x7fc73be4e1d8?, {0x0, 0x0})
	/home/winlist/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.13.0/neo4j/internal/router/router.go:154 +0xb5
github.com/neo4j/neo4j-go-driver/v5/neo4j/internal/router.(*Router).GetOrUpdateWriters(0xc00027c500, {0x1ca5630, 0xc008772dc0}, 0x40df65?, {0x1996373, 0x5}, 0x1?, {0x0, 0x0})
	/home/winlist/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.13.0/neo4j/internal/router/router.go:256 +0x5e
github.com/neo4j/neo4j-go-driver/v5/neo4j.(*sessionWithContext).getOrUpdateServers(0xc006fa5e00, {0x1ca5630, 0xc008772dc0}, 0x5?)
	/home/winlist/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.13.0/neo4j/session_with_context.go:512 +0x125
github.com/neo4j/neo4j-go-driver/v5/neo4j.(*sessionWithContext).getConnection(0xc006fa5e00, {0x1ca5668?, 0xc009cb1030?}, 0x0, 0x40ff49?)
	/home/winlist/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.13.0/neo4j/session_with_context.go:543 +0x387
github.com/neo4j/neo4j-go-driver/v5/neo4j.(*sessionWithContext).executeTransactionFunction(0xc006fa5e00, {0x1ca5668, 0xc009cb1030}, 0x0, {0x5?, 0x0?}, 0xc006f455c0, 0xc0078084c0, 0xf8?, 0x3)
	/home/winlist/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.13.0/neo4j/session_with_context.go:443 +0x9f
github.com/neo4j/neo4j-go-driver/v5/neo4j.(*sessionWithContext).runRetriable(0xc006fa5e00, {0x1ca5668, 0xc009cb1030}, 0x1912760?, 0x27bc0a0?, 0x70?, 0x7fc73be4e1d8?, {0x0, 0x0, 0x0})
	/home/winlist/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.13.0/neo4j/session_with_context.go:424 +0x2c9
github.com/neo4j/neo4j-go-driver/v5/neo4j.(*sessionWithContext).executeQueryWrite(0xc0078084c0?, {0x1ca5668?, 0xc009cb1030?}, 0x410805?, {0x0?, 0x1912760?, 0xc0068a4f01?})
	/home/winlist/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.13.0/neo4j/session_with_context.go:383 +0x45
github.com/neo4j/neo4j-go-driver/v5/neo4j.ExecuteQuery[...]({0x1ca5668, 0xc009cb1030?}, {0x1ca9a30, 0xc0000f61c0}, {0x1a01231, 0x1ba}, 0xc009cf6030, 0x1a1f9b8, {0xc0068a52a8, 0x1, ...})
	/home/winlist/go/pkg/mod/github.com/neo4j/neo4j-go-driver/v5@v5.13.0/neo4j/driver_with_context.go:548 +0x4fe
...
```
This is how I am connecting with my neo4j instance

```go
        logger.Info("Connecting to Neo4J", "config", neo4jConfig)
	ctx := context.Background()
	driver, err := neo4j.NewDriverWithContext(
		neo4jConfig.Host,
		neo4j.BasicAuth(
			neo4jConfig.UserName,
			neo4jConfig.Password,
			"",
		),
		func(c *neo4jconfig.Config) {
			c = neo4jconfig.
		},
	)
```
and this is how I query

```go
	result, err := neo4j.ExecuteQuery(ctx, *l.neo4jDriver,
		"neo4j query here",
		map[string]any{
			"jpins":          jpins,
			"customerGrpIds": customerGrpIds,
		}, neo4j.EagerResultTransformer,
		neo4j.ExecuteQueryWithDatabase("neo4j"),
		neo4j.ExecuteQueryWithReadersRouting(),
	)
	if err != nil {
		...
	}
	...
```

- Neo4j version: 4.4-aura/enterprise
- Neo4j Mode: Single instance with 2 followers
- Driver version: GoLang driver v5.13.0
- Operating system: Ubuntu 16.04.4 LTS x86_64 on AWS

**Steps to reproduce**
I don't know why or when this happens, or how to reproduce this.

### PR DESCRIPTION
**Pull request by DaChartreux**
In method getOrUpdate, if a goroutine is waiting for the routing table to be updated by that one goroutine which is updating the routing table, it pushes a channel into updating map. But when the goroutine reaches its deadline (or times-out), and the goroutine which was updating the table tries to send `struct{}{}` to the channel, there is no goroutine there to receive and this causes deadlock. Instead of pushing empty struct, we should be closing the channel instead. Which is safe of panics or deadlocks.

### CODE REVIEW

**Comment by StephenCathcart** [comment]
Hi @DaChartreux 

Thank you for taking the time to contribute to a Neo4j project, we appreciate all community engagement.
Before we review a change we require that users have signed our Contributor License Agreement(CLA). This allows the "whitelist-check (pull-request)" part of our build process to pass.
For more details on signing our CLA please see: https://neo4j.com/developer/cla/. Specifically the 'How to Sign' section.

**Comment by StephenCathcart** [comment]
Hi @DaChartreux, I've received your CLA and added you to our whitelist database. My colleagues and I reviewed the PR and are fairly confident this will fix the bug you're experiencing. We're just doing some further testing around this before merging the fix. I'll keep you up to date with how this is progressing. 

Thanks again for your contribution!

**Comment by DaChartreux** [comment]
Hi @StephenCathcart! Thanks for the whitelist. Let me know if there are any inputs.

**Comment by StephenCathcart** [comment]
Hi @DaChartreux, our whitelist-check step is still failing. After a bit of investigation, it seems this is due to the author of the actual commits in the PR (Amit Parameshwar) not matching the name that was whitelisted (DaChartreux) in our database.

If possible, would you be able to either get the other identity (Amit) to also sign the CLA, or create a new PR with the now whitelisted DaChartreux identity as the committer which should pass? Apologies for the inconvenience.

**Pull request closed without merging**
