### PR TITLE
feat: bolt struct point modify #0000

### PR DESCRIPTION
**Pull request by xiongpan828**
bolt point modify

### CODE REVIEW

**Comment by fbiville** [comment]
Hell and welcome 👋
What are you trying to achieve here?
Let's start with a [discussion](https://github.com/neo4j/neo4j-go-driver/discussions) here first, what do you think?

**Comment by xiongpan828** [comment]
Hi thanks for your reply
I mainly want to improve the structure pointer in the code

**Comment by fbiville** [comment]
Thanks for the reply @xiongpan828. What are you looking to improve exactly?
What problem did you initially spot that this PR fixes?

**Comment by fbiville** [comment]
I'm happy to reopen the pull request once we discuss in more details what motivates the changes (either in a [discussion](https://github.com/neo4j/neo4j-go-driver/discussions) or an [issue](https://github.com/neo4j/neo4j-go-driver/issues/new)).

**Pull request closed without merging**
