### PR TITLE
Enhance Neo4j integration test configuration For Feature Request #428

### PR DESCRIPTION
**Pull request by lucapirolo**
- Add `getVersionFromDB` to `DbServer` for dynamic version detection
- Remove default version in `VersionOf` if empty
- Default `GetDbServer` to localhost when `TEST_NEO4J_HOST` unset
- https://github.com/neo4j/neo4j-go-driver/issues/428

### CODE REVIEW

**Comment by StephenCathcart** [comment]
Hi @lucapirolo 

Thank you for taking the time to contribute to a Neo4j project, we appreciate all community engagement.
Before we review a change we require that users have signed our Contributor License Agreement(CLA). This allows the "whitelist-check (pull-request)" part of our build process to pass.
For more details on signing our CLA please see: https://neo4j.com/developer/cla/. Specifically the 'How to Sign' section.

Apologies for any inconvenience!

**Comment by lucapirolo** [comment]
Hi @StephenCathcart, I've completed and signed the CLA agreement. Could you please rerun the pipeline? Assuming my CLA submission has been accepted, it should now pass the whitelist check. Thank you!

**Comment by StephenCathcart** [comment]
> Hi @StephenCathcart, I've completed and signed the CLA agreement. Could you please rerun the pipeline? Assuming my CLA submission has been accepted, it should now pass the whitelist check. Thank you!

Hi @lucapirolo, I can confirm we received the agreement and I've updated the whitelist database. I'll rerun the pipeline in a moment 👍.

**Comment by lucapirolo** [comment]
Hi @StephenCathcart,

I noticed that the testkit-neo4j-go-driver check is currently failing. If it's an issue related to the code, please let me know – I'm ready and available to assist in resolving it!

**Review by StephenCathcart — APPROVED** [review]
Changes look good to me 👍, runs fine on my end too

**Pull request merged**
