### PR TITLE
Removed dep instructions from the README

### PR DESCRIPTION
**Pull request by wagnerjt**
* Removed the dep instructions from the readme to encourage go modules (see below reasoning). 
* Altered some md linting issues

From deps' github page: 
> dep was the "official experiment." The Go toolchain, as of 1.11, has adopted an approach that sharply diverges from dep. As a result, we are continuing development of dep, but gearing work primarily towards the development of an alternative prototype for versioning behavior in the toolchain.

I targeted the `1.8-dev` branch for this PR because go modules is included

### CODE REVIEW

**Comment by 2hdddg** [comment]
@wagnerjt thanks for your pull request! To be able to merge any changes you need to sign our CLA: https://neo4j.com/developer/cla/

Just to be clear, the 1.8-dev is under construction so you should not use that one for any development work right now, there are still a lot of functionality missing compared to 1.7. The work being done here is primarily to get rid of dependency on cgo.

**Comment by wagnerjt** [comment]
@2hdddg -- appreciate the reminder on the CLA. I recently sent my signature to the address under those instructions :).  

As for the targeted `1.8-dev` branch, I wanted to bump this small when go modules were introduced. And it appears it happened during the pure golang refactoring. I could target this PR towards the `1.7` branch, but I would need the cgo dep configured correctly as well to test everything out.

**Comment by 2hdddg** [comment]
@wagnerjt  I can merge this one on the 1.8 branch in a while. The 1.7 shouldn't be needed in the long run.

**Comment by 2hdddg** [comment]
@wagnerjt could you please rebase this against 1.8
Neo4j CI pipeline is about to be up and running which means that verfification of signed CLA (and of course testing) will start to kick in.

**Comment by 2hdddg** [comment]
Most of the fixes in this has been merged from 1.8-dev to 1.8 by now

**Pull request closed without merging**
