### PR TITLE
Add new notification categories `SECURITY` and `TOPOLOGY`

### PR DESCRIPTION
**Pull request by StephenCathcart**
Added Topology and Security notification categories to align with the new categories as of the 5.14 server.

### CODE REVIEW

**Comment by StephenCathcart** [comment]
[Add new notification categories SECURITY and TOPOLOGY to drivers [Go]](https://trello.com/c/PMe9YlBx/71-add-new-notification-categories-security-and-topology-to-drivers-go)

**Review by thelonelyvulpes — APPROVED** [review]
Simple, and clean.

**Review by bigmontz — APPROVED** [review]
🥇 

(Is there not tests for this?)

**Review by robsdedude — APPROVED** [review]
:no_bell:

**Comment by StephenCathcart** [comment]
> 🥇
> 
> (Is there not tests for this?)

I thought this too but the other notifications don't seem to have any, maybe I should look at adding more unit tests around this 👍

**Pull request merged**
