### PR TITLE
Readme typo

### PR DESCRIPTION
**Pull request by pzurek**
A little fix for `the` used twice in a row.

### CODE REVIEW

**Comment by 2hdddg** [comment]
Hi @pzurek you need to sign our  CLA: https://neo4j.com/developer/cla/ (even for just a simple typo). If that is too much to do for this typo I will fix it. Thanks anyway

**Comment by pzurek** [comment]
I've sent the CLA email with a bcc to you for confirmation.

I'll use this opportunity to thank you for all the work on creating a pure Go version of the driver. It finally makes using Neo4j as painless as any other DB. 👏 👏 👏 👏

**Comment by 2hdddg** [comment]
@pzurek can you please rebase your pull request to trigger whitelist check?

**Comment by pzurek** [comment]
@2hdddg Looks like TeamCity has a problem with this. Let's not waste anymore of your time on this. It's not like it's a groundbreaking contribution. 😀

**Pull request closed without merging**
