### PR TITLE
chore: fix driver manual link in README

### PR DESCRIPTION
**Pull request by julienvey**

### CODE REVIEW

**Comment by thelonelyvulpes** [comment]
Hello, thank you for taking the time to contribute to a Neo4j project, we appreciate all community engagement. 
Before we review a change we require that users have signed our Contributor License Agreement(CLA).
For more details on signing our CLA please see: https://neo4j.com/developer/cla/

**Comment by fbiville** [comment]
@julienvey have you had a chance to sign the CLA yet?

**Comment by julienvey** [comment]
@fbiville Yes, I sent the email a few days ago. I haven't received a reply yet

**Comment by fbiville** [comment]
It's all good, then. Let me get this merged before the 5.6.0 release today.

**Pull request merged**
