### PR TITLE
Close session to release conn pool and fix typo

### PR DESCRIPTION
**Pull request by dynastymasra**
Close session to release the connection pool when calling method VerifyConnectivity and fix type on driver comment

### CODE REVIEW

**Comment by 2hdddg** [comment]
Nice work!
You need to sign our CLA for your PR to be mergable:
https://neo4j.com/developer/cla/

**Comment by dynastymasra** [comment]
> https://neo4j.com/developer/cla/

Hi @2hdddg 
I have already signed the CLA.
thank you for your response

**Comment by dynastymasra** [comment]
Hi @2hdddg 
How about the status of this PR?

**Comment by 2hdddg** [comment]
Hi @dynastymasra 
Still having failures with the CLA in our internal builds. This has been fixed on 4.0 branch and that will soon be released so I'm closing this PR now as there are no more planned 1.8 releases.
Thank you very much for finding this and submitting the PR.

**Pull request closed without merging**
